// Universal Media Downloader Type System & Data Contracts

export enum ProviderCapability {
  DIRECT_DOWNLOAD = "DIRECT_DOWNLOAD",
  METADATA_ONLY = "METADATA_ONLY",
  SEARCH_FALLBACK = "SEARCH_FALLBACK",
  PLAYLIST = "PLAYLIST",
  AUDIO = "AUDIO",
  VIDEO = "VIDEO",
  THUMBNAIL = "THUMBNAIL",
  SUBTITLE = "SUBTITLE",
  CANDIDATE_SCORING = "CANDIDATE_SCORING",
  LOCAL_INSPECTION = "LOCAL_INSPECTION",
  UNSUPPORTED = "UNSUPPORTED",
}

export type PlatformCategory =
  | "video"
  | "music"
  | "social"
  | "short_video"
  | "messaging"
  | "streaming"
  | "creative"
  | "community"
  | "other";

export interface MediaFormatOption {
  id: string;
  type: "video" | "audio" | "image";
  quality: string;
  container: string;
  codec?: string;
  bitrate?: string;
  sampleRate?: string;
  resolution?: string;
  fps?: number;
  sizeBytes?: number;
  sizeLabel?: string;
  isEstimated?: boolean;
  url: string;
  source: "native" | "api" | "fallback" | "external";
  isDirectStream?: boolean;
  downloadable: boolean;
  requiresAuth?: boolean;
  requiresFallback?: boolean;
  expiresAt?: number;
}

export interface ThumbnailOption {
  id: string;
  quality: string;
  resolution: string;
  format: "jpg" | "png" | "webp";
  url: string;
  sizeLabel?: string;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  languageCode: string;
  format: "vtt" | "srt" | "ttml";
  isAutoGenerated?: boolean;
  url: string;
}

export interface CandidateMatch {
  id: string;
  title: string;
  artist?: string;
  durationSeconds?: number;
  durationLabel?: string;
  thumbnailUrl: string;
  streamUrl: string;
  confidenceScore: number; // 0 to 100
  matchReasons: string[];
  sourceProvider: string;
  isOfficial?: boolean;
}

export interface CollectionItemSummary {
  index: number;
  id: string;
  title: string;
  artist?: string;
  durationLabel?: string;
  thumbnailUrl?: string;
  canonicalUrl: string;
  status: "pending" | "resolving" | "ready" | "downloading" | "completed" | "failed";
  progress?: number;
  error?: string;
  selectedFormat?: MediaFormatOption;
}

export interface MediaCollectionInfo {
  id: string;
  title: string;
  type: "playlist" | "album" | "channel" | "collection";
  author?: string;
  totalItems: number;
  thumbnailUrl?: string;
  items: CollectionItemSummary[];
}

export interface NormalizedMedia {
  id: string;
  originalUrl: string;
  canonicalUrl: string;
  platformId: string;
  platformName: string;
  category: PlatformCategory;
  capabilities: ProviderCapability[];
  title: string;
  description?: string;
  author?: string;
  authorUrl?: string;
  durationSeconds?: number;
  durationLabel?: string;
  viewCount?: number;
  likeCount?: number;
  thumbnail: string;
  thumbnails: ThumbnailOption[];
  formats: MediaFormatOption[];
  subtitles: SubtitleTrack[];
  collection?: MediaCollectionInfo;
  candidateMatches?: CandidateMatch[];
  selectedCandidate?: CandidateMatch;
  previewUrl?: string;
  previewType?: "video" | "audio" | "image";
  fallbackNote?: string;
  diagnostics?: {
    extractionDurationMs: number;
    backendUsed: string;
    cached?: boolean;
  };
}

export enum JobState {
  QUEUED = "QUEUED",
  RESOLVING = "RESOLVING",
  FETCHING = "FETCHING",
  DOWNLOADING = "DOWNLOADING",
  PROCESSING = "PROCESSING",
  VERIFYING = "VERIFYING",
  READY = "READY",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLING = "CANCELLING",
  CANCELLED = "CANCELLED",
}

export interface DownloadJob {
  id: string;
  url: string;
  title: string;
  platformId: string;
  state: JobState;
  progress: number; // 0 to 100
  speedLabel?: string;
  downloadedBytes?: number;
  totalBytes?: number;
  selectedFormat: MediaFormatOption;
  downloadUrl?: string;
  outputPath?: string;
  error?: string;
  createdAt: number;
  updatedAt: number;
  completedAt?: number;
  expiresAt: number;
  isBatch?: boolean;
  batchTotal?: number;
  batchCompleted?: number;
}

export interface ProviderCatalogItem {
  id: string;
  name: string;
  category: PlatformCategory;
  color: string;
  iconName: string;
  domains: string[];
  supportedMediaTypes: ("video" | "audio" | "image" | "subtitles")[];
  supportedCapabilities: ProviderCapability[];
  deliveryMode: "DIRECT_DOWNLOAD" | "SEARCH_FALLBACK" | "METADATA_ONLY" | "LOCAL_INSPECTION";
  hasPlaylistSupport: boolean;
  hasMetadataSupport: boolean;
  status: "healthy" | "degraded" | "unavailable" | "checking";
  latencyMs: number;
  totalSuccesses: number;
  totalErrors: number;
  lastChecked: number;
  description: string;
  unavailableReason?: string;
  exampleUrl: string;
}

export interface PlatformHealthStatus extends ProviderCatalogItem {}
