import { ProviderCatalogItem, ProviderCapability, PlatformCategory } from "../types/media";

export const ALL_PLATFORM_CATALOG: ProviderCatalogItem[] = [
  // 1. Video Category
  {
    id: "youtube",
    name: "YouTube & Shorts",
    category: "video",
    color: "#FF0000",
    iconName: "Youtube",
    domains: ["youtube.com", "www.youtube.com", "m.youtube.com", "youtu.be"],
    supportedMediaTypes: ["video", "audio", "image", "subtitles"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.PLAYLIST,
      ProviderCapability.AUDIO,
      ProviderCapability.VIDEO,
      ProviderCapability.THUMBNAIL,
      ProviderCapability.SUBTITLE,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: true,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 142,
    totalSuccesses: 1840,
    totalErrors: 2,
    lastChecked: Date.now(),
    description: "4K, 1440p, 1080p, 720p MP4 videos, dedicated 320kbps MP3 audio, multi-res thumbnails, and subtitles.",
    exampleUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "bilibili",
    name: "Bilibili",
    category: "video",
    color: "#00A1D6",
    iconName: "Tv",
    domains: ["bilibili.com", "www.bilibili.com", "b23.tv"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 310,
    totalSuccesses: 420,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "Full HD anime, gaming clips, and creator videos with audio extraction.",
    exampleUrl: "https://www.bilibili.com/video/BV1xx411c7mD",
  },
  {
    id: "vimeo",
    name: "Vimeo",
    category: "video",
    color: "#1AB7EA",
    iconName: "Video",
    domains: ["vimeo.com", "player.vimeo.com"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 195,
    totalSuccesses: 610,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Original cinematic videos in 1080p and 4K without compression loss.",
    exampleUrl: "https://vimeo.com/76979871",
  },
  {
    id: "dailymotion",
    name: "Dailymotion",
    category: "video",
    color: "#0066DC",
    iconName: "Film",
    domains: ["dailymotion.com", "dai.ly"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 240,
    totalSuccesses: 340,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "High-definition news, documentaries, and entertainment videos.",
    exampleUrl: "https://www.dailymotion.com/video/x7tgad0",
  },

  // 2. Music Streaming Category
  {
    id: "youtube_music",
    name: "YouTube Music",
    category: "music",
    color: "#FF0000",
    iconName: "Music",
    domains: ["music.youtube.com"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.AUDIO,
      ProviderCapability.PLAYLIST,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: true,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 160,
    totalSuccesses: 1200,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Studio 320kbps MP3 audio, full artist albums, playlists, and original album artwork.",
    exampleUrl: "https://music.youtube.com/watch?v=dQw4w9WgXcQ",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "music",
    color: "#1DB954",
    iconName: "Radio",
    domains: ["spotify.com", "open.spotify.com", "spotify.link"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.METADATA_ONLY,
      ProviderCapability.SEARCH_FALLBACK,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
      ProviderCapability.CANDIDATE_SCORING,
    ],
    deliveryMode: "SEARCH_FALLBACK",
    hasPlaylistSupport: true,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 180,
    totalSuccesses: 2950,
    totalErrors: 3,
    lastChecked: Date.now(),
    description: "Official track metadata, 640x640 artwork, ISRC, and confidence-scored equivalent studio stream matching.",
    exampleUrl: "https://open.spotify.com/track/4cOdK2wGLETKBW3PvgPWqT",
  },
  {
    id: "apple_music",
    name: "Apple Music",
    category: "music",
    color: "#FC3C44",
    iconName: "Apple",
    domains: ["music.apple.com", "apple.com"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.METADATA_ONLY,
      ProviderCapability.SEARCH_FALLBACK,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
      ProviderCapability.CANDIDATE_SCORING,
    ],
    deliveryMode: "SEARCH_FALLBACK",
    hasPlaylistSupport: true,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 220,
    totalSuccesses: 1120,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "Curated lossless metadata, High-Res cover artwork, and verified candidate stream matching.",
    exampleUrl: "https://music.apple.com/us/album/never-gonna-give-you-up/1559523357?i=1559523359",
  },
  {
    id: "amazon_music",
    name: "Amazon Music",
    category: "music",
    color: "#00A8E1",
    iconName: "Headphones",
    domains: ["music.amazon.com", "amazon.com"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.METADATA_ONLY,
      ProviderCapability.SEARCH_FALLBACK,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "SEARCH_FALLBACK",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 250,
    totalSuccesses: 430,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Public track & album metadata with legal candidate search-match stream resolution.",
    exampleUrl: "https://music.amazon.com/albums/B00138GY52",
  },
  {
    id: "jiosaavn",
    name: "JioSaavn",
    category: "music",
    color: "#2BC5B4",
    iconName: "Music2",
    domains: ["jiosaavn.com", "saavn.com"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.METADATA_ONLY,
      ProviderCapability.SEARCH_FALLBACK,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "SEARCH_FALLBACK",
    hasPlaylistSupport: true,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 190,
    totalSuccesses: 870,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Bollywood, Hindi, Punjabi, and Regional Indian music metadata and candidate streams.",
    exampleUrl: "https://www.jiosaavn.com/song/kesariya/HzwbeBVfV1s",
  },
  {
    id: "gaana",
    name: "Gaana",
    category: "music",
    color: "#E72C30",
    iconName: "Disc",
    domains: ["gaana.com"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.METADATA_ONLY,
      ProviderCapability.SEARCH_FALLBACK,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "SEARCH_FALLBACK",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 210,
    totalSuccesses: 510,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "Indian regional songs and podcast metadata with candidate audio matching.",
    exampleUrl: "https://gaana.com/song/kesariya-from-brahmastra",
  },
  {
    id: "soundcloud",
    name: "SoundCloud",
    category: "music",
    color: "#FF5500",
    iconName: "Volume2",
    domains: ["soundcloud.com", "snd.sc"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: true,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 175,
    totalSuccesses: 1680,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Original independent artist tracks, DJ sets, remix audio streams, and cover art.",
    exampleUrl: "https://soundcloud.com/artist/track",
  },
  {
    id: "audiomack",
    name: "Audiomack",
    category: "music",
    color: "#FFA200",
    iconName: "Music",
    domains: ["audiomack.com"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 185,
    totalSuccesses: 390,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Hip-hop, electronic, and afrobeat audio streams and album art.",
    exampleUrl: "https://audiomack.com/song/artist/track",
  },
  {
    id: "bandcamp",
    name: "Bandcamp",
    category: "music",
    color: "#629AA9",
    iconName: "Disc3",
    domains: ["bandcamp.com"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: true,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 205,
    totalSuccesses: 620,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Indie artist lossless audio, discography metadata, and merchandise artwork.",
    exampleUrl: "https://artist.bandcamp.com/track/song",
  },
  {
    id: "mixcloud",
    name: "Mixcloud",
    category: "music",
    color: "#5000FF",
    iconName: "Sliders",
    domains: ["mixcloud.com"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 230,
    totalSuccesses: 290,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Long-form DJ sets, radio broadcasts, and podcast audio streams.",
    exampleUrl: "https://www.mixcloud.com/dj/mix/",
  },
  {
    id: "qq_music",
    name: "QQ Music",
    category: "music",
    color: "#31C27C",
    iconName: "Music",
    domains: ["y.qq.com", "qq.com"],
    supportedMediaTypes: ["audio", "image"],
    supportedCapabilities: [
      ProviderCapability.METADATA_ONLY,
      ProviderCapability.SEARCH_FALLBACK,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "SEARCH_FALLBACK",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 380,
    totalSuccesses: 210,
    totalErrors: 2,
    lastChecked: Date.now(),
    description: "Mandopop, C-Pop, and Asian music metadata with legal search matching.",
    exampleUrl: "https://y.qq.com/n/ryqq/songDetail/001",
  },
  {
    id: "weverse",
    name: "Weverse",
    category: "community",
    color: "#00E0D0",
    iconName: "Users",
    domains: ["weverse.io"],
    supportedMediaTypes: ["video", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 340,
    totalSuccesses: 190,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "K-Pop global artist community posts, public live clips, and media.",
    exampleUrl: "https://weverse.io/artist/media",
  },

  // 3. Social Platforms Category
  {
    id: "instagram",
    name: "Instagram & Reels",
    category: "social",
    color: "#E4405F",
    iconName: "Instagram",
    domains: ["instagram.com", "www.instagram.com", "instagr.am"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 155,
    totalSuccesses: 3400,
    totalErrors: 4,
    lastChecked: Date.now(),
    description: "1080p Instagram Reels, Stories, video posts, carousel photos, and audio extraction.",
    exampleUrl: "https://www.instagram.com/reel/C1234567890/",
  },
  {
    id: "facebook",
    name: "Facebook & Watch",
    category: "social",
    color: "#1877F2",
    iconName: "Facebook",
    domains: ["facebook.com", "www.facebook.com", "fb.watch", "fb.com", "m.facebook.com"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 190,
    totalSuccesses: 1780,
    totalErrors: 2,
    lastChecked: Date.now(),
    description: "Full HD and SD public Facebook videos, Reels, and Watch streams.",
    exampleUrl: "https://fb.watch/example123/",
  },
  {
    id: "threads",
    name: "Threads",
    category: "social",
    color: "#000000",
    iconName: "MessageCircle",
    domains: ["threads.net", "www.threads.net"],
    supportedMediaTypes: ["video", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 170,
    totalSuccesses: 540,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Direct video clips and high-resolution photos from Threads posts.",
    exampleUrl: "https://www.threads.net/@user/post/example",
  },
  {
    id: "twitter",
    name: "X (Twitter) & Trends",
    category: "social",
    color: "#1DA1F2",
    iconName: "Twitter",
    domains: ["twitter.com", "x.com", "t.co"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 165,
    totalSuccesses: 2210,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "Original MP4 videos, animated GIFs, audio spaces snippets, and full-resolution images.",
    exampleUrl: "https://twitter.com/user/status/1234567890",
  },
  {
    id: "reddit",
    name: "Reddit",
    category: "community",
    color: "#FF4500",
    iconName: "MessageSquare",
    domains: ["reddit.com", "redd.it", "v.redd.it"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 195,
    totalSuccesses: 1450,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "Native Reddit videos with automatically synchronized audio, galleries, and GIFs.",
    exampleUrl: "https://www.reddit.com/r/videos/comments/abc123/example/",
  },
  {
    id: "discord",
    name: "Discord CDN",
    category: "messaging",
    color: "#5865F2",
    iconName: "MessageSquare",
    domains: ["discord.com", "discordapp.com", "cdn.discordapp.com"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 140,
    totalSuccesses: 890,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Direct media attachments, video clips, and voice messages from public Discord channels.",
    exampleUrl: "https://cdn.discordapp.com/attachments/123/456/video.mp4",
  },
  {
    id: "telegram",
    name: "Telegram Channels",
    category: "messaging",
    color: "#229ED9",
    iconName: "Send",
    domains: ["t.me", "telegram.me"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 225,
    totalSuccesses: 730,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Public channel media, voice notes, and videos without file size throttling.",
    exampleUrl: "https://t.me/channel/123",
  },
  {
    id: "tumblr",
    name: "Tumblr",
    category: "creative",
    color: "#35465C",
    iconName: "FileText",
    domains: ["tumblr.com"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 210,
    totalSuccesses: 310,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "High-resolution photo sets, audio tracks, and animated video posts.",
    exampleUrl: "https://username.tumblr.com/post/123456",
  },
  {
    id: "vk",
    name: "VK (VKontakte)",
    category: "social",
    color: "#4C75A3",
    iconName: "Share2",
    domains: ["vk.com"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 280,
    totalSuccesses: 460,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "Public VK video clips, music playlists, and wall media.",
    exampleUrl: "https://vk.com/video-123_456",
  },

  // 4. Short Video Category
  {
    id: "tiktok",
    name: "TikTok (No Watermark)",
    category: "short_video",
    color: "#00F2FE",
    iconName: "Zap",
    domains: ["tiktok.com", "www.tiktok.com", "douyin.com"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 148,
    totalSuccesses: 4100,
    totalErrors: 3,
    lastChecked: Date.now(),
    description: "Watermark-free HD 1080p MP4 videos, original music MP3 extraction, and full-res covers.",
    exampleUrl: "https://www.tiktok.com/@tiktok/video/7106594312292453678",
  },
  {
    id: "snapchat",
    name: "Snapchat Spotlight",
    category: "short_video",
    color: "#FFFC00",
    iconName: "Camera",
    domains: ["snapchat.com"],
    supportedMediaTypes: ["video", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 215,
    totalSuccesses: 680,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "Public Spotlight vertical videos, lens clips, and public creator stories.",
    exampleUrl: "https://www.snapchat.com/spotlight/12345",
  },
  {
    id: "triller",
    name: "Triller",
    category: "short_video",
    color: "#E91E63",
    iconName: "Video",
    domains: ["triller.co"],
    supportedMediaTypes: ["video", "audio"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 260,
    totalSuccesses: 240,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "High-energy music video clips and short-form creator content.",
    exampleUrl: "https://triller.co/@user/video/123",
  },
  {
    id: "moj",
    name: "Moj App",
    category: "short_video",
    color: "#FF5722",
    iconName: "Flame",
    domains: ["mojapp.in"],
    supportedMediaTypes: ["video", "audio"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 235,
    totalSuccesses: 580,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "Indian short video app content without watermark.",
    exampleUrl: "https://mojapp.in/@user/video/123",
  },
  {
    id: "sharechat",
    name: "ShareChat",
    category: "short_video",
    color: "#2196F3",
    iconName: "Share2",
    domains: ["sharechat.com"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 250,
    totalSuccesses: 490,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Multilingual Indian regional posts, videos, and music clips.",
    exampleUrl: "https://sharechat.com/post/123",
  },
  {
    id: "likee",
    name: "Likee",
    category: "short_video",
    color: "#FF007F",
    iconName: "Heart",
    domains: ["likee.video", "like-video.com"],
    supportedMediaTypes: ["video", "audio"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 220,
    totalSuccesses: 630,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Vibrant short videos with special visual effects and audio track extraction.",
    exampleUrl: "https://likee.video/@user/video/123",
  },

  // 5. Messaging & Privacy Category
  {
    id: "whatsapp_status",
    name: "WhatsApp Web Status Saver",
    category: "messaging",
    color: "#25D366",
    iconName: "Phone",
    domains: ["web.whatsapp.com", "whatsapp.com", "wa.me"],
    supportedMediaTypes: ["video", "image"],
    supportedCapabilities: [
      ProviderCapability.LOCAL_INSPECTION,
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "LOCAL_INSPECTION",
    hasPlaylistSupport: true,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 20,
    totalSuccesses: 5200,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "In-browser local status inspector. 100% private sandbox with zero cloud data transfer.",
    exampleUrl: "https://web.whatsapp.com",
  },

  // 6. Streaming Category
  {
    id: "twitch",
    name: "Twitch Clips",
    category: "streaming",
    color: "#9146FF",
    iconName: "Tv2",
    domains: ["twitch.tv", "clips.twitch.tv"],
    supportedMediaTypes: ["video", "audio"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 180,
    totalSuccesses: 1150,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Full HD livestream highlights, gaming clips, and creator VODs.",
    exampleUrl: "https://clips.twitch.tv/ExampleClipName",
  },
  {
    id: "rumble",
    name: "Rumble",
    category: "streaming",
    color: "#85C742",
    iconName: "PlayCircle",
    domains: ["rumble.com"],
    supportedMediaTypes: ["video", "audio"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 195,
    totalSuccesses: 740,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "High-definition video streams and creator shows.",
    exampleUrl: "https://rumble.com/v12345-video.html",
  },

  // 7. Creative & Community Category
  {
    id: "pinterest",
    name: "Pinterest",
    category: "creative",
    color: "#BD081C",
    iconName: "Pin",
    domains: ["pinterest.com", "pin.it"],
    supportedMediaTypes: ["video", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 160,
    totalSuccesses: 2100,
    totalErrors: 1,
    lastChecked: Date.now(),
    description: "Original 4K & Ultra HD photo pins, design artworks, and video Idea Pins.",
    exampleUrl: "https://www.pinterest.com/pin/123456789/",
  },
  {
    id: "linkedin",
    name: "LinkedIn Video",
    category: "creative",
    color: "#0A66C2",
    iconName: "Briefcase",
    domains: ["linkedin.com"],
    supportedMediaTypes: ["video", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.THUMBNAIL,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 210,
    totalSuccesses: 820,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Professional presentations, keynote videos, and carousel media.",
    exampleUrl: "https://www.linkedin.com/posts/example",
  },
  {
    id: "patreon",
    name: "Patreon",
    category: "community",
    color: "#FF424D",
    iconName: "HeartHandshake",
    domains: ["patreon.com"],
    supportedMediaTypes: ["video", "audio", "image"],
    supportedCapabilities: [
      ProviderCapability.DIRECT_DOWNLOAD,
      ProviderCapability.VIDEO,
      ProviderCapability.AUDIO,
    ],
    deliveryMode: "DIRECT_DOWNLOAD",
    hasPlaylistSupport: false,
    hasMetadataSupport: true,
    status: "healthy",
    latencyMs: 240,
    totalSuccesses: 410,
    totalErrors: 0,
    lastChecked: Date.now(),
    description: "Public creator podcasts, artwork, and video posts.",
    exampleUrl: "https://www.patreon.com/posts/example-12345",
  },
];
